version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
  # garnet:
  #   restart: always
  #   image: garnet
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3278:3278"